name: Canary Community App Build

on:
  push:
    branches:
      - canary-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.FITER_DOCKER_USERNAME }}
          password: ${{ secrets.FITER_DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          repository: fiter1/community-app/canary-community-app
          tags: latest